site_name: Wiki-Fan
site_author: Wiki-Fan
copyright: Copyright &copy; 2024 Wiki-Fan
site_url: https://mydomain.org/mysite
repo_url: https://github.com/squidfunk/mkdocs-material

# markdown_extentions:
#   - admonition

nav:
  - 主页: index.md
  - 工具:
      - 基础:
        - 配置参考: 
          - 主题配置: 个人/config.md
  # - 关于: 



theme:
  name: material
  features:
    - content.code.copy # 代码块复制按钮
    - content.action.edit # 文章编辑按钮
    #- navigation.instant # Instant loading，像个单页应用
    - navigation.tracking # Anchor tracking
    - navigation.tabs # 导航栏
    - navigation.footer # 上一篇 / 下一篇导航按钮
    #- navigation.tabs.sticky # 导航栏不随页面滚动隐藏
    - navigation.sections # 侧边栏分组显示
    #- navigation.expand # 导航栏自动展开
    - navigation.indexes # 组标题有专属页面
    - toc.follow # 目录自动跟随
    - navigation.top # 返回顶部按钮
    - search.suggest # 搜索推荐
    #- navigation.prune # 导航修剪，仅渲染可见链接，优化文档数量超过100的站点（实验），会导致页面间跳转速度变慢
    #- search.highlight
  icon:
    repo: material/github
    #edit: material/pencil

  # name: material
  font: #false # 国内网络访问 Google 源可能会有问题
    text: "Noto Sans SC - local"
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)" # 检查用户系统配置是否为亮色
      scheme: default # 亮色模式
      primary: white # 基本颜色
      accent: blue # 按钮等互动块的颜色
      toggle:
        icon: material/eye
        name: 切换暗色模式
    - media: "(prefers-color-scheme: dark)" # 检查用户系统配置是否为暗色
      scheme: slate # 暗色模式
      primary: black # 基本颜色
      accent: blue # 按钮等互动块的颜色
      toggle:
        icon: material/eye-outline
        name: 切换亮色模式
  language: zh
    # - primary: white
    # - accent: blue


# markdown_extensions:
#   - admonition  # 提示块
#   - footnotes  # 脚注
#   - meta  # 定义元数据，通过文章上下文控制，如disqus
#   - pymdownx.caret  # 下划线上标
#   - pymdownx.tilde  # 删除线下标
#   - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
#   - pymdownx.details  # 提示块可折叠
#   - pymdownx.inlinehilite  # 行内代码高亮
#   - pymdownx.mark  # 文本高亮
#   - pymdownx.smartsymbols  # 符号转换
#   - pymdownx.superfences  # 代码嵌套在列表里
#   - codehilite:    # 代码高亮，显示行号
#       guess_lang: false
#       linenums: true
#   - toc:  # 锚点
#       permalink: true
# #  - pymdownx.arithmatex  # 数学公式
#   - pymdownx.betterem:  # 对加粗和斜体更好的检测
#       smart_enable: all
# #  - pymdownx.emoji:  # 表情
# #      emoji_generator: !!python/name:pymdownx.emoji.to_svg
# #  - pymdownx.magiclink  # 自动识别超链接
#   - pymdownx.tasklist:  # 复选框checklist
#       custom_checkbox: true

# plugins:
#   - search
#   # - blog
#   - social
#   - tags


# #扩展样式
# extra_css:
#   - resources/css/extra.css
